name: CI
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      checks: write

    steps:
      - name: Checkout source
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435

      - name: Docker Compose Build (pull latest base)
        run: docker compose build --pull

      - name: Run RSpec with coverage and JUnit output
        run: |
          mkdir -p tmp/coverage tmp/rspec
          docker compose run --rm -u 0:0 dev \
            bash -c "bundle exec rspec --format progress --format RspecJunitFormatter --out tmp/rspec/results.xml"
        env:
          SIMPLECOV: true

      - name: Upload test results
        uses: dorny/test-reporter@dc3a92680fcc15842eef52e8c4606ea7ce6bd3f3
        if: always()
        with:
          name: RSpec Reports
          path: tmp/rspec/results.xml
          reporter: java-junit
        continue-on-error: true

      - name: Copy coverage artifacts
        run: |
          mkdir -p artifacts
          cp -r ./coverage artifacts/ || true
          cp -r ./tmp/rspec artifacts/ || true

      - name: Relax permissions for artifacts
        run: chmod -R a+rX tmp coverage artifacts || true

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: rspec-coverage
          path: artifacts/

  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout source
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435

      - name: Docker Compose Build (cacheable)
        run: docker compose build

      - name: Run RuboCop
        run: |
          mkdir -p tmp artifacts
          # Run inside container; ensure pipeline returns non-zero on RuboCop failure
          docker compose run --rm -u 0:0 dev bash -c 'set -o pipefail; bundle exec rubocop | tee tmp/rubocop.log'
          status=$?
          # Always collect the log for artifacts
          cp tmp/rubocop.log artifacts/ || true
          exit $status

      - name: Relax permissions for artifacts
        run: chmod -R a+rX tmp artifacts || true

      - name: Upload RuboCop artifacts (if any)
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: rubocop-logs
          path: artifacts/

  bundler_audit:
    name: Bundler Audit
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout source
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435

      - name: Docker Compose Build (cacheable)
        run: docker compose build

      - name: Run bundler-audit
        run: |
          mkdir -p tmp
          set -o pipefail
          docker compose run --rm -u 0:0 dev bash -c "bundle exec bundler-audit update && bundle exec bundler-audit check -v" | tee tmp/bundler-audit.log

      - name: Relax permissions for artifacts
        run: chmod -R a+rX tmp artifacts || true

      - name: Upload bundler-audit logs (if any)
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: bundler-audit-logs
          path: tmp/bundler-audit.log
